apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sql-after-wordpress-pvc
  labels:
    app: after-wordpress-sql
    tier: after-wordpress
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: after-wordpress-sql
  labels:
    app: after-wordpress-sql
spec:
  type: ClusterIP
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: after-wordpress-sql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: after-wordpress-sql
  labels:
    app: after-wordpress-sql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: after-wordpress-sql
  template:
    metadata:
      labels:
        app: after-wordpress-sql
    spec:
      containers:
        - image: mysql:8.0
          name: after-wordpress-sql
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: after-wordpress
            - name: MYSQL_DATABASE
              value: after-wordpress-db
            - name: MYSQL_USER
              value: after-wordpress-user
            - name: MYSQL_PASSWORD
              value: after-wordpress-2024
          ports:
            - containerPort: 3306
              name: mysql-port
          volumeMounts:
            - name: mysql-pv-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-pv-storage
          persistentVolumeClaim:
            claimName: sql-after-wordpress-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: after-wordpress-pvc
  labels:
    app: after-wordpress
    tier: after-wordpress
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: after-wordpress
  name: after-wordpress
spec:
  type: NodePort
  selector:
    app: after-wordpress
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      nodePort: 30180  # NodePortを30180に変更
      name: http-port
    - port: 22               # SSH用の22番ポートを追加
      targetPort: 22
      protocol: TCP
      nodePort: 32122        # NodePortで公開するポートを32122に設定
      name: ssh-port
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: after-wordpress
  labels:
    app: after-wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: after-wordpress
  template:
    metadata:
      labels:
        app: after-wordpress
    spec:
      containers:
        - image: c0a21099/wp-nginx-rsync
          name: after-wordpress
          env:
            - name: WORDPRESS_DB_HOST
              value: after-wordpress-sql
            - name: WORDPRESS_DB_NAME
              value: after-wordpress-db
            - name: WORDPRESS_DB_USER
              value: after-wordpress-user
            - name: WORDPRESS_DB_PASSWORD
              value: after-wordpress-2024
          ports:
            - containerPort: 80
              name: wordpress-port
            - containerPort: 22   # SSH用のポートを追加
              name: ssh-port
          volumeMounts:
            - name: wordpress-pv-storage
              mountPath: /var/www/html
      volumes:
        - name: wordpress-pv-storage
          persistentVolumeClaim:
            claimName: after-wordpress-pvc
