apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  # 名前は自由に設定できます
  name: deployment-reader-cluster
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list"]
