apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: deployment-reader-binding
subjects:
- kind: ServiceAccount
  name: default
  namespace: front-end
roleRef:
  kind: ClusterRole
  name: deployment-reader-cluster
  apiGroup: rbac.authorization.k8s.io
